###
POST http://localhost:5000/register
Content-Type: application/json

{
    "email" : "asep@gmail.com",
    "password" : "1234rewq"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "selva@gmail.com",
    "password" : "1234rewq"
}

