###
POST https://jvalleylogin.herokuapp.com/register
Content-Type: application/json

{
    "email" : "asep@gmail.com",
    "password" : "1234rewq"
}

###
POST https://jvalleylogin.herokuapp.com/login
Content-Type: application/json

{
    "email" : "selva@gmail.com",
    "password" : "1234rewq"
}

